export const UPDATE_PRODUCTS = Symbol('UPDATE_PRODUCTS');
export const UPDATE_CURRENT_PRODUCT = Symbol('UPDATE_CURRENT_PRODUCT');
export const UPDATE_ACTIVE_FILTERS = Symbol('UPDATE_ACTIVE_FILTERS');
